### ISSUE TITLE
magento-1.9-patch-1533-5344 returns error message

### ISSUE THREAD

**Issue by Dr3am3rz** [sashas777/magento-1.9-patch-1533-5344#1]
Hi, I have updated the files accordingly to what you have provided. Thanks for the effort.

However, I have come across an error after finish updating.

Fatal error: Call to undefined method Mage_Core_Controller_Request_Http::getInternallyForwarded() in /home/avenuesg/public_html/app/code/core/Mage/Admin/Model/Observer.php on line 73

I have no idea how to fix it.

Appreciate for your help.

**Comment by sashas777** [comment]
Hi there was missing Http.php File .

**Comment by dynasty2015** [comment]
Hi. I uploaded the patch files including the Http.php file but afterwards could not access the website. I got an error saying the server could not process the request.

**Comment by sashas777** [comment]
Hi,
Did you disabled cache & compilation mode ? What is yours Magento version?

**Comment by dynasty2015** [comment]
My Magento version is 1.8. How do I disable cache and compilation mode?

**Comment by sashas777** [comment]
I just updated and compared file. Could you try it ?
For compilation mode check includes/config.php file. The both define lines should be commented there ( begin with #)

**Comment by dynasty2015** [comment]
Yes, the update does not seem to causing any issues now. Thanks for the fix.

**Comment by LittleLukas** [comment]
Have the same issue. Magento 1.9.1 . Tried everything above but doesn't work for me.

**Comment by sashas777** [comment]
Have you replaced Http.php file?

**Comment by LittleLukas** [comment]
There wasn’t what replace. Because there are no folders  ->Controller->Request->Http.php.

So I created and added your file Http.php

 

 

Gediminas

Thank you

 

Find Us On:  <https://www.facebook.com/littlelukas2011> social_facebook_box_blue_16  <https://plus.google.com/+Littlelukas/posts> google-plus  <https://twitter.com/Little_Lukas> social_twitter_box_blue_16  <http://www.pinterest.com/littlelukas/> pinterest-16x16  <https://www.youtube.com/channel/UCPHy9A_1-lzfjd8yAW8Tk3w> 1362896765_youtube  <http://www.linkedin.com/company/littlelukas/> linkedin

 <http://www.littlelukas.com/> logo

 

The contents of this email may be confidential. If you have received this email in error please inform the sender and delete this email. Any comments expressed are those of the author and may be reflective of The Company’s view.
